# Generated by Django 5.2.2 on 2025-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
