# Generated by Django 5.2.2 on 2025-06-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color')},
        ),
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
    ]
