# Generated by Django 5.2.2 on 2025-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
