# Generated by Django 5.2.2 on 2025-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variant_unique_together_color_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.ManyToManyField(to='store.size'),
        ),
    ]
