# Generated by Django 5.2.2 on 2025-06-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
        ('order', '0005_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingaddress'),
        ),
    ]
