# Generated by Django 5.2.2 on 2025-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='alternative_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
